version: '3.8'

services:
    PrecipitationDb:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD = Password1!
        ports:
            - 3310:3306
    TemperatureDb:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD = Password1!
        ports:
          - '3311:3306'
    WeatherReportDb:
      image: mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD = Password1!
