FROM mcr.microsoft.com/sdk:7.0 as build-env

WORKDIR /app

COPY . .

RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/aspnet:7.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT [ "dotnet", "DotNet.Docker.dll" ]