version: '3.8'

services:
    PrecipitationDb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password1!
            MYSQL_DATABASE: PrecipitationDb
        ports:
            - '3310:3306'
    TemperatureDb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password1!
            MYSQL_DATABASE: TemperatureDb
        ports:
            - '3311:3306'
    WeatherReportDb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password1!
            MYSQL_DATABASE: WeatherReportDb
        ports:
          - '3312:3306'
